### ISSUE TITLE
New attack technique: Login via AWS EC2 Serial Console

### ISSUE THREAD

**Issue by siigil** [DataDog/stratus-red-team#531] opened 2024-07-02 14:04 UTC
Login via Serial Ports: AWS
https://unit42.paloaltonetworks.com/cloud-virtual-machine-attack-vectors/

**Comment by siigil** [comment] 2024-07-02 14:05
Suggested tags: kind/new-technique, platform/aws

**Comment by christophetd** [comment] 2024-08-27 12:22
duplicate of https://github.com/DataDog/stratus-red-team/issues/487

**Closed by christophetd** 2024-08-27 12:22 UTC
Labels: kind/new-technique, platform/aws
