### ISSUE TITLE
aws.execution.ec2-launch-unusual-instances working

### ISSUE THREAD

**Issue by agroyz** [DataDog/stratus-red-team#387] opened 2023-07-20 21:09 UTC
This is a new issue. This started with the latest build. 

BTW, thanks for adding in this output. **[DEBUG] Successfully assumed role!** . 

**What is not working?**
detonate aws.execution.ec2-launch-unusual-instances

Ubuntu 22.04.2 LTS

**What is your Stratus Red Team version?**
2.8.0

 ./stratus detonate aws.execution.ec2-launch-unusual-instances
2023/07/20 21:03:01 Checking your authentication against AWS
2023/07/20 21:03:01 Not warming up - aws.execution.ec2-launch-unusual-instances is already warm. Use --force to force
2023/07/20 21:03:01 [DEBUG] Successfully assumed role!
2023/07/20 21:03:01 Attempting to run up to 10 instances of type p2.xlarge
2023/07/20 21:03:02 Error while detonating attack technique aws.execution.ec2-launch-unusual-instances: expected ec2:RunInstances to return an access denied error, got instead: operation error EC2: RunInstances, https response error StatusCode: 403, RequestID: 993a3d41-5543-43ff-850e-dd3a79685bd5, api error UnauthorizedOperation: You are not authorized to perform this operation. Encoded authorization failure message: qoYeuy5DNQMk_k7JauWsrjPnqAi9h90gWITrdEQKpzKtUH4C4XeRuGX_uviYK9_27hWRbK5Pf9jBrs08Gsd23YlGh_1Df9onGQUbfcih720lVZzTMbVKIVJTFFxPLGEQHV-rFoSMAj3Q99K34ugMR00dIp_RWoySKoNNKilmkiwxep_aJ_pvimWGZgcisM3SkFh0Sx4FShxUw5Cff4AGrK9YkJIt2ScBA4SqoMpbkV9snWa8m00Y2ZnWBbNYi-thhu28GjtZ0p0VEZFQCxCuNIsxcZIgTVwe0GTeezjhEJC12Etmk_SEhlDVZ1w9G-1Mk_jbPNoi48X9_2YUTjxxIfCCZ_d5y8W9OYyBmozp33Q4wbL6xLRcCEh9lbcfnPHje2m9NPh5QrY94uFEiuih1DMTQTJCQEY0NjMaCf_U6j31tyECRo1xbAjOXSH-GslMH703sscMHYx0Ccz3iRTYEHw8FlTmhI9-l7ZpKEGN0tleGpOA5tRXYAnJfqxELlX16YnrpbV4JeK67kKmrVf4xOzkTBRKvNKgoCA9-IVxQyhF0dLMqn09IZfNNFy6K-4RukWcsD-M1Ym6LzhXba-FB7kkUiUx6R5h0R0lpjG4osiusgq3MNYswRSWxRNLK8ie97WOZ9JGbj4E6TxTti5DuPDWXjmaZ5Al8bV1TILXqkVTl8a3hm2fR1V6jhlVDaQMhpAMegiUR6Yp4TG2bFpOAnozHKwYmg

**Comment by christophetd** [comment] 2023-07-24 09:23
Thanks for reporting! Can you share a version number that does not have this issue? I'm currently unable to reproduce in my test AWS account on 2.8.0

**Comment by christophetd** [comment] 2023-07-24 09:35
Was actually able to reproduce

**Comment by christophetd** [comment] 2023-07-25 09:28
Fixed in #390 and will be shortly released in Stratus Red Team v2.8.1

**Closed** 2023-07-25 09:27 UTC
Labels: kind/bug, platform/aws, status/confirmed

**Comment by Nurlan199206** [comment] 2024-07-30 03:23
i have same error via terraform...

 `Error: creating EC2 Instance: operation error EC2: RunInstances, https response error StatusCode: 403, RequestID: 7f14fcf4-8f18-47b1-be18-482beb868c04, api error UnauthorizedOperation: You are not authorized to perform this operation. User: arn:aws:iam::058916088911:user/terraform is not authorized to perform: ec2:RunInstances on resource: arn:aws:ec2:eu-central-1:058916088911:instance/* with an explicit deny in an identity-based policy. Encoded authorization failure message: alWVZTKUUTtBHhgj8P5PY-WQ_-sZ5U3Fhzx47Fzn4np7YimtmKyFn2w5uX6ZnC8X0yHOvmvS2MSPE_BMxb3t8AuV6jUwd3Pd-9xFqhmvMc22GKKiTrhpHleIf9nWKVA4Of3vPcCWQR7v878T4w7p5CJ-3Fhqfnk9qMhLCQ02EU1q_heIbC9ccsRqJCYqOrAsUGGsT2B9Ii5SGtLZqnWoFQbeSU1vVkmi_GWVE1kwNKHEf81CHj9jVgsO150p7UmoGpK_uvOdk1Mh-0HRPX12RwhfvlgQmaR-7PtZllpoa26tPibePodFt7N-5OYaq1ZGnEhhKtaZNQBXettuklLK-Mlbh_l5AZxDsJIhWMM06RwtM83jfJ-4ydNNWGtBwHoBhyrpBJ8Boj45CV3t6gZcj7g-GJugp94oqJsM6VtbfGzgEc9wTCwd5SJOwWYJ2Y71jr6X-nFwd0m_TxwlELg2eg9rvMj1rhu5Hjv1GBLna1y9ajXAgU6HcItFDZc0_yev5Hjl5_-ZUJMOMhSdnZ8Q6JLcxqlLG1jESh6FoYtuzF1uVzWQE75HyX6w9uD_d8uhmX9CIE3aJfvIMmtIo1bCnM681EJDrRhLZpnaT6aFLXuBNr1xy7wQx0wBwAWVZQaQLy6i37gE6fvMb0ZJWSJuZoUDdIX9dmKNkkIy49OXmGBNQoEb8L2fiAoEA4QicDYFw6sIGSCrYpHZH5rHfAv2mg30N_9bIPADqUlkeReOoYi99lgj7eO2zh6khbQIw26rTAu6tHQheadcku40-cH2Rr4L-74q_e4gmfJZJJU1dScC7aWuJkLpM5O0sVDoaNagabIu--V3TL--JTOUqq4LUzUGO22NK1X7w8F_z_3YOFoIgbAavNYGa6BLCQzd99sLRexcVXqHqT98S3ovcqwMJs8SxEsM1WzGcPnhCqkwHdeSjX6z2Hf-N5mj15-qGjkTjXRgDcchB88rsuw_i9elR8DblCic5I5iP_6TaLn8JQc0EByxYRk-j9odfcIMMjB9EcNF5Voagb2CN1oTUEv9dvUJD1OpWCO3zpT6x-XrUsyr1oeleY8KKNWowD3cHiLeA6WHnPAfy7_gNYX753EVSzA6g4QxdDdx6QepKi64t0VxFcEBQU-VcT0fttU4ZCQtkNw87bZpRcELwmj2MBTDqYDYLAmu5nXh4VLhJ6fOYCgKn5VZONpxwO5OHBHk8VqNKoe6V_IJxL4GkL-9SDGCBnuHR5MrTVR_CLOwnnV_iRcRvmeHtcedtJ4r4ceu4GrhBnXA32OkK_wBDQHJcr0hTTV6jZyvRwZsmxhRfa1coKRJpo-lw6B9bn7zHY6MQW0ft_9IRsmF-lKuAH5dNi2Wo5r5aVMsXaM5LdpIDxrJG8dFyaqW01rqbQ6-kYPUG4ThLvMvavnw20q62jl0SMVZROMdTHaDFlX3XRSbqN4fa0hmoawGXkbxcNXEMBa23JMKOZeIkjTZcPnFfu1ULZQ64ZwHnsQwWDhYbfIOOoCeRqSmWhAX2WozaS0fzC74K7CfmnlS6RR13gtUTBDA2_4

`

**Comment by Nurlan199206** [comment] 2024-07-30 03:31
...

![image](https://github.com/user-attachments/assets/653f0155-db4f-4090-935d-4102248145d5)
